epumanagement:
  service_name: epu_management_service
  provisioner_service_name: provisioner
  initial_definitions: {}
  initial_domains: {}
  needy_default_iaas_site: site-1
  needy_default_iaas_allocation: t1.micro
  provisioner_vars: {}
