server:
  amqp:
    host: localhost
    port: 5672
    username: guest
    password: guest
    vhost: /
    heartbeat: 30
logging:
  version: 1
  formatters:
    brief:
      format: '%(levelname)-8s %(message)s'
    default:
      format: '%(asctime)s %(levelname)-8s %(name)-15s %(message)s'
      datefmt: '%Y-%m-%d %H:%M:%S'
    detailed:
      format: '%(asctime)s.%(msecs)03d [%(module)-15s:%(lineno)3d] %(levelname)-5s:%(message)s'
      datefmt: '%Y-%m-%d %H:%M:%S'
    detailednostamp:
      format: '[%(module)-15s:%(lineno)3d] %(levelname)-5s:%(message)s'

  handlers:
    console:
      class: logging.StreamHandler
      formatter: detailed
      level: DEBUG
      stream: ext://sys.stdout
    file:
      class: logging.handlers.RotatingFileHandler
      formatter: detailed
      level: DEBUG
      filename: logs/logfile.txt
      maxBytes: 1048576
      backupCount: 3
    syslog:
      class: logging.handlers.SysLogHandler
      address: [localhost, 514]
      formatter: detailednostamp
      level: DEBUG
      facility: local0
  loggers:
    epu:
      level: DEBUG
    dashi:
      level: INFO
  root:
    handlers: [console, file]
    level: DEBUG
